import path from "path"
import { fileURLToPath } from "url"
import fs from "fs"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const snapshotPath = path.join(dir, "src/provider/models-snapshot.js")

// Skip if snapshot already exists (avoid network dependency during local builds)
if (fs.existsSync(snapshotPath) && process.env.MIMOCODE_REGENERATE_MODELS !== "true") {
  console.log("Models snapshot already exists, skipping generation")
} else {
  const modelsUrl = process.env.MIMOCODE_MODELS_URL || "https://models.dev"
  // Fetch and generate models.dev snapshot
  const modelsData = process.env.MODELS_DEV_API_JSON
    ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
    : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
  await Bun.write(
    snapshotPath,
    `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
  )
  await Bun.write(
    path.join(dir, "src/provider/models-snapshot.d.ts"),
    `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
  )
  console.log("Generated models-snapshot.js")
}
